name: Deploy to Minikube

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        shell: powershell
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image
        run: docker build -t namduong0606/golang-portal:latest .

      - name: Push image
        run: docker push namduong0606/golang-portal:latest

      - name: Rollout deployment
        run: |
          kubectl rollout restart deployment/golang-portal
          kubectl rollout status deployment/golang-portal
